[pytest]
norecursedirs =
    pymembrane/cppmodule/md/external/pybind11
    pymembrane/cppmodule/build
    pymembrane/cppmodule/md/build
addopts =
    --ignore=pymembrane/cppmodule/tests/test_benchmark_edge_flip.py
    --ignore=pymembrane/cppmodule/md/external/pybind11/tests
